Add model layer, move there the the generating points logic.
kirpichonok/Auto-Clicker-App pull request #11
Opened 2023-12-08 08:03 UTC by kirpichonok

# What

Add class `PointsGeneratorModel` to encapsulate the generating points logic.

# How 

- Add class `PointsGeneratorModel`

- Move generating points logic from the `MainScreenVM` to the `PointsGeneratorModel`.

2023-12-08 12:40 UTC, vkostechko-applace requested changes

2023-12-08 12:40 UTC, vkostechko-applace commented on Auto-Clicker-App/Auto-Clicker-App/MainScreen/PointsGeneratorModel.swift
> +class PointsGeneratorModel {
final?

2023-12-08 12:40 UTC, vkostechko-applace commented on Auto-Clicker-App/Auto-Clicker-App/MainScreen/PointsGeneratorModel.swift
> +    @Published var point: CGPoint?
private(set)?

2023-12-08 12:40 UTC, vkostechko-applace commented on Auto-Clicker-App/Auto-Clicker-App/MainScreen/PointsGeneratorModel.swift
> +    private func reset() {
please keep file structure 

- properties (public/private)
- init / overrides 
- public methods
- private methods
- protocols

2023-12-08 12:40 UTC, vkostechko-applace commented on Auto-Clicker-App/Auto-Clicker-App/MainScreen/PointsGeneratorModel.swift
> +        counter = 3
I suggest to move 3 to constants 
<img width="580" alt="BirbankInvest_—_ProcessingScreenViewModelImpl_swift" src="https://github.com/kirpichonok/Auto-Clicker-App/assets/152169284/1333bf1b-9b0b-443f-8911-ae8a428dfc1e">

2023-12-11 06:31 UTC, kirpichonok commented on Auto-Clicker-App/Auto-Clicker-App/MainScreen/PointsGeneratorModel.swift
> +    private func reset() {
Fixed.

2023-12-11 06:31 UTC, kirpichonok commented on Auto-Clicker-App/Auto-Clicker-App/MainScreen/PointsGeneratorModel.swift
> +class PointsGeneratorModel {
Fixed.

2023-12-11 06:48 UTC, kirpichonok commented on Auto-Clicker-App/Auto-Clicker-App/MainScreen/PointsGeneratorModel.swift
> +        counter = 3
We're going to have settings for these values, and I use an **instance** of the `PointsGeneratorModel` class. I think it's more appropriate to use instance properties to change the behavior of the specified model instance.
It's good idea to set static property for `maxAmoutOfPointers = 5` or `maxRetryDelay: TimeInterval = 60.0` (according to design model).
WDYT?

2023-12-11 09:26 UTC, vkostechko-applace approved these changes

2023-12-11 09:26 UTC, merged